/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Comisiones: typeof import('./src/components/Comisiones.vue')['default']
    copy: typeof import('./src/components/NuevoUsuario copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Monitor: typeof import('./src/components/Monitor.vue')['default']
    NuevaSesion: typeof import('./src/components/NuevaSesion.vue')['default']
    NuevoRegistroAcreditacion: typeof import('./src/components/NuevoRegistroAcreditacion.vue')['default']
    NuevoRegistroComisiones: typeof import('./src/components/NuevoRegistroComisiones.vue')['default']
    NuevoUsuario: typeof import('./src/components/NuevoUsuario.vue')['default']
    ReportesCentral: typeof import('./src/components/ReportesCentral.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seguimiento: typeof import('./src/components/Seguimiento.vue')['default']
    SeguimientoAcreditacion: typeof import('./src/components/SeguimientoAcreditacion.vue')['default']
    SeguimientoComisiones: typeof import('./src/components/SeguimientoComisiones.vue')['default']
    SeguimientoRepresentaciones: typeof import('./src/components/SeguimientoRepresentaciones.vue')['default']
  }
}
